# Generated by Django 3.1 on 2020-09-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date')),
                ('url', models.URLField(verbose_name='Video URL')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
